### ISSUE TITLE
Wrong solution

### ISSUE THREAD

**Issue by Ridery1** [seratne/salvations-edge-verity#5]
As you can see, solution is wrong for some reason
https://imgur.com/a/TL8w0Lk

**Comment by Nightknight3000** [comment]
Was able to reproduce this.

**Comment by Nightknight3000** [comment]
Interesting... Did this actually occur for you? Because I never had two of the same kind of 3D shapes (though this may just be a rare case).
Correct steps would be:
1. Place Triangle on **left** and Circle on **right**
2. Place Square on **middle** and Circle on **right**

Right?

**Comment by iximeow** [comment]
> (though this may just be a rare case)

it's not _super_ rare, i've definitely seen two of the same 3D shape a few times (cone cone cube, prism prism sphere, from memory)

the steps you listed would be correct, yes

**Comment by Ridery1** [comment]
> Interesting... Did this actually occur for you? Because I never had two of the same kind of 3D shapes (though this may just be a rare case). Correct steps would be:
> 
> 1. Place Triangle on **left** and Circle on **right**
> 2. Place Square on **middle** and Circle on **right**
> 
> Right?

Yepp, this happened with my team, thats why i've posted it here:) Can share a video if it's needed.

**Comment by JKammeier** [comment]
I had a very similar issue right now:
https://imgur.com/nhpp7El
