### ISSUE TITLE
Incorrect solution being shown

### ISSUE THREAD

**Issue by RajatMittal1995** [seratne/salvations-edge-verity#7]
Hello,
Thanks for this tool, I came across a combination which messes up the tool.

Below Image shows the tool solution, which is incorrect:
![image](https://github.com/seratne/salvations-edge-verity/assets/9135666/54a7028e-8bd1-4557-b0a4-95af9dbe8f82)

Below image shows actual solution:
![image](https://github.com/seratne/salvations-edge-verity/assets/9135666/e20520e4-3bb5-4d15-85e3-ae4ad05da4b1)

**Comment by Nightknight3000** [comment]
This kind of problem has already been reported with this issue: https://github.com/seratne/salvations-edge-verity/issues/5.

**Comment by RajatMittal1995** [comment]
Noted! Just wanted to make sure it is highlighted :) 
Cheers!

**Comment by RajatMittal1995** [comment]
Issue Fixed!
